### ISSUE TITLE
[Q] What will happen if your rabbitmq-connector crashes?

### ISSUE THREAD

**Issue by zadigus** [Templum/rabbitmq-connector#265]
The way I understand your code, the rabbitmq-connector is a rabbitmq consumer. It consumes messages out of the rabbitmq, maps the message with the relevant function, waits until the function returns; upon function result reception, the rabbitmq-connector sends back an acknowledgment (or a failure) to rabbitmq. 

In order to be able to send the right acknowledgement of the right function to rabbitmq, the rabbitmq-connector consumer needs to maintain a state. Currently, it is an in-memory map. 

My question is: what will happen if the rabbitmq-connector consumer has just called a function and suddenly crashes, and the function's return value has not been obtained yet? Is that resolved in this way that rabbitmq never gets an acknowledgment / failure confirmation and takes the consumed message back in the queue?

I'm sorry for that noob question, I am not very familiar with the rabbitmq works.

**Comment by Templum** [comment]
Actually, you got it right the message is only leaving the queue if it gets acked. So if the consumer/connector crashes before it can send the ack,  it will go back to the queue. And get picked up at a later point in time.

Each message taken from rabbit has a reservation time, which binds it to a consumer. That's why the message won't be at the "top" of the queue.

**Comment by Templum** [comment]
Let me know if that answered your question

**Comment by Templum** [comment]
Let me know if that answered your question, and further you may leverage the [discussions](https://github.com/Templum/rabbitmq-connector/discussions/categories/q-a) in the future for questions.

**Comment by zadigus** [comment]
Ok thanks for your explanations.
